import { Buyer } from './buyer.model';
import { BuyerDemand } from './buyerDemand.model';

export async function seedDemoBuyers() {
  try {
    const existingCount = await Buyer.countDocuments();
    if (existingCount > 0) {
      return;
    }

    console.log('Seeding PRISMS Demo Buyers & Buyer Demands dataset...');

    const demoBuyers = [
      {
        buyerId: 'BUYER-DEMO-001',
        businessName: 'Nashik Agro Processors Ltd.',
        buyerType: 'Processor',
        location: 'Pimpalgaon Baswant',
        district: 'Nashik',
        state: 'Maharashtra',
        cropsInterested: ['Red Onion', 'Onion', 'Tomato'],
        preferredGrades: ['Grade A', 'Grade B', 'A', 'B'],
        minQuantityQtl: 20,
        maxQuantityQtl: 150,
        targetPriceMin: 2400,
        targetPriceMax: 3600,
        deliveryPreference: 'Factory Gate Delivery or Local APMC Pickup',
        paymentTerms: 'Immediate Bank Transfer (Simulated Escrow)',
        verificationStatus: 'Sample Buyer Profile',
        isDemo: true,
        description: 'Commercial dehydrated onion and paste processing unit operating in Nashik district.',
        contactPhone: '+91 98221 11001 (Demo)',
        contactEmail: 'procurement@nashikagro.demo',
      },
      {
        buyerId: 'BUYER-DEMO-002',
        businessName: 'Mumbai Metro Wholesale Foods',
        buyerType: 'Institutional Buyer',
        location: 'Vashi Market Yard',
        district: 'Navi Mumbai',
        state: 'Maharashtra',
        cropsInterested: ['Tomato', 'Red Onion', 'Potato', 'Green Chilli'],
        preferredGrades: ['Grade A', 'A'],
        minQuantityQtl: 30,
        maxQuantityQtl: 200,
        targetPriceMin: 2800,
        targetPriceMax: 4200,
        deliveryPreference: 'Vashi APMC Terminal Direct Delivery',
        paymentTerms: 'T+1 Direct Bank Transfer (Simulated)',
        verificationStatus: 'Sample Buyer Profile',
        isDemo: true,
        description: 'Bulk institutional distributor serving hotel chains and retail outlets across MMR region.',
        contactPhone: '+91 98221 22002 (Demo)',
        contactEmail: 'vashi.bulk@metrowholesale.demo',
      },
      {
        buyerId: 'BUYER-DEMO-003',
        businessName: 'Maharashtra Grain & Flour Mills',
        buyerType: 'Wholesaler',
        location: 'Hadapsar Industrial Zone',
        district: 'Pune',
        state: 'Maharashtra',
        cropsInterested: ['Wheat', 'Soybeans'],
        preferredGrades: ['Grade A', 'FAQ', 'A', 'B'],
        minQuantityQtl: 50,
        maxQuantityQtl: 300,
        targetPriceMin: 2300,
        targetPriceMax: 2700,
        deliveryPreference: 'Warehouse Delivery (Pune)',
        paymentTerms: 'Same-day NEFT (Simulated)',
        verificationStatus: 'Sample Buyer Profile',
        isDemo: true,
        description: 'Major regional grain flour miller purchasing high-protein Wheat and Soybeans.',
        contactPhone: '+91 98221 33003 (Demo)',
        contactEmail: 'procurement@mhgrains.demo',
      },
      {
        buyerId: 'BUYER-DEMO-004',
        businessName: 'Sahyadri Fresh Retail Supermarkets',
        buyerType: 'Retail Chain',
        location: 'Satara Road Hub',
        district: 'Satara',
        state: 'Maharashtra',
        cropsInterested: ['Tomato', 'Banana', 'Red Onion'],
        preferredGrades: ['Grade A', 'A'],
        minQuantityQtl: 15,
        maxQuantityQtl: 80,
        targetPriceMin: 2600,
        targetPriceMax: 3800,
        deliveryPreference: 'Cold Chain Pickup / Hub Delivery',
        paymentTerms: 'Weekly Settlement (Simulated)',
        verificationStatus: 'Sample Buyer Profile',
        isDemo: true,
        description: 'Direct-to-consumer supermarket chain seeking fresh premium Grade A produce.',
        contactPhone: '+91 98221 44004 (Demo)',
        contactEmail: 'sahyadri.fresh@retail.demo',
      },
      {
        buyerId: 'BUYER-DEMO-005',
        businessName: 'Mahagrapes & Fruit Exporters',
        buyerType: 'Exporter',
        location: 'Solapur MIDC',
        district: 'Solapur',
        state: 'Maharashtra',
        cropsInterested: ['Banana', 'Red Onion', 'Cotton'],
        preferredGrades: ['Grade A', 'Export Grade'],
        minQuantityQtl: 40,
        maxQuantityQtl: 250,
        targetPriceMin: 3200,
        targetPriceMax: 5500,
        deliveryPreference: 'Port Packhouse Delivery (JNPT / Navi Mumbai)',
        paymentTerms: 'Immediate Advance Escrow (Simulated)',
        verificationStatus: 'Sample Buyer Profile',
        isDemo: true,
        description: 'Agricultural export consortium sourcing export-grade bananas, onions, and cotton.',
        contactPhone: '+91 98221 55005 (Demo)',
        contactEmail: 'export@mahagrapes.demo',
      },
      {
        buyerId: 'BUYER-DEMO-006',
        businessName: 'Kisan Producer Company (FPO Aggregator)',
        buyerType: 'FPO Aggregator',
        location: 'Rahuri APMC Enclave',
        district: 'Ahmednagar',
        state: 'Maharashtra',
        cropsInterested: ['Soybeans', 'Wheat', 'Cotton', 'Potato'],
        preferredGrades: ['FAQ', 'Grade B', 'Grade A'],
        minQuantityQtl: 25,
        maxQuantityQtl: 180,
        targetPriceMin: 2200,
        targetPriceMax: 4800,
        deliveryPreference: 'FPO Collection Center Pickup',
        paymentTerms: 'Immediate Member Account Transfer (Simulated)',
        verificationStatus: 'Sample Buyer Profile',
        isDemo: true,
        description: 'Farmer Producer Organization aggregating member produce for bulk institutional auctions.',
        contactPhone: '+91 98221 66006 (Demo)',
        contactEmail: 'aggregator@kisanfpo.demo',
      },
    ];

    await Buyer.insertMany(demoBuyers);

    const futureDate = new Date();
    futureDate.setDate(futureDate.getDate() + 45);

    const demoDemands = [
      {
        buyerId: 'BUYER-DEMO-001',
        commodity: 'Red Onion',
        variety: 'Garwa / Lasalgaon Red',
        requiredGrade: 'Grade A',
        minQuantityQtl: 20,
        maxQuantityQtl: 120,
        targetPriceMin: 2500,
        targetPriceMax: 3500,
        deliveryLocation: 'Pimpalgaon, Nashik',
        demandStatus: 'ACTIVE',
        validUntil: futureDate,
        isDemo: true,
        notes: 'Seeking medium to large sized firm onions for dehydration.',
      },
      {
        buyerId: 'BUYER-DEMO-001',
        commodity: 'Onion',
        variety: 'Nasik Local',
        requiredGrade: 'Grade B',
        minQuantityQtl: 30,
        maxQuantityQtl: 150,
        targetPriceMin: 2200,
        targetPriceMax: 2900,
        deliveryLocation: 'Pimpalgaon, Nashik',
        demandStatus: 'ACTIVE',
        validUntil: futureDate,
        isDemo: true,
        notes: 'Grade B onions accepted for paste processing.',
      },
      {
        buyerId: 'BUYER-DEMO-002',
        commodity: 'Tomato',
        variety: 'Hybrid Narayangaon',
        requiredGrade: 'Grade A',
        minQuantityQtl: 30,
        maxQuantityQtl: 150,
        targetPriceMin: 2800,
        targetPriceMax: 4000,
        deliveryLocation: 'Vashi APMC, Navi Mumbai',
        demandStatus: 'ACTIVE',
        validUntil: futureDate,
        isDemo: true,
        notes: 'Firm red tomatoes required for hotel distribution.',
      },
      {
        buyerId: 'BUYER-DEMO-003',
        commodity: 'Wheat',
        variety: 'Sharbati / Lokwan',
        requiredGrade: 'FAQ',
        minQuantityQtl: 50,
        maxQuantityQtl: 300,
        targetPriceMin: 2350,
        targetPriceMax: 2650,
        deliveryLocation: 'Hadapsar, Pune',
        demandStatus: 'ACTIVE',
        validUntil: futureDate,
        isDemo: true,
        notes: 'Moisture content under 12% required.',
      },
      {
        buyerId: 'BUYER-DEMO-004',
        commodity: 'Tomato',
        variety: 'Local Hybrid',
        requiredGrade: 'Grade A',
        minQuantityQtl: 15,
        maxQuantityQtl: 60,
        targetPriceMin: 2600,
        targetPriceMax: 3600,
        deliveryLocation: 'Satara Road, Satara',
        demandStatus: 'ACTIVE',
        validUntil: futureDate,
        isDemo: true,
        notes: 'Uniform color and size required for retail display.',
      },
      {
        buyerId: 'BUYER-DEMO-005',
        commodity: 'Banana',
        variety: 'Grand Naine',
        requiredGrade: 'Grade A',
        minQuantityQtl: 40,
        maxQuantityQtl: 200,
        targetPriceMin: 1800,
        targetPriceMax: 2600,
        deliveryLocation: 'Solapur Packhouse / JNPT',
        demandStatus: 'ACTIVE',
        validUntil: futureDate,
        isDemo: true,
        notes: 'Unblemished green bunches for cold-chain container shipment.',
      },
      {
        buyerId: 'BUYER-DEMO-006',
        commodity: 'Soybeans',
        variety: 'Yellow Soybeans',
        requiredGrade: 'Grade A',
        minQuantityQtl: 25,
        maxQuantityQtl: 150,
        targetPriceMin: 4400,
        targetPriceMax: 4900,
        deliveryLocation: 'Rahuri, Ahmednagar',
        demandStatus: 'ACTIVE',
        validUntil: futureDate,
        isDemo: true,
        notes: 'High oil percentage preference for oil mill contracts.',
      },
    ];

    await BuyerDemand.insertMany(demoDemands);
    console.log('PRISMS Demo Buyers & Buyer Demands seeded successfully!');
  } catch (err) {
    console.error('Error seeding demo buyers:', err);
  }
}
